### PR TITLE
Minor tweak

### PR DESCRIPTION
**Pull request by caderaspindrift**
Changed RMagick to rmagick

### CODE REVIEW

**Comment by nodanaonlyzuul** [comment]
Hi @caderaspindrift 

Thanks so much for contributing.
It's been so long since I've given this gem the attention is deserves.

I've double checked that downcasing to 'rmagick' works - does the rmagick library prefer the downcased version? Or is using 'RMagick' deprecated in newer versions of the rmagick library?

Thanks again.

**Comment by nodanaonlyzuul** [comment]
Oh - now I see that this is in reference to https://github.com/nodanaonlyzuul/asciiart/issues/7.
I'm going to give this a spin on a debian machine. (Your branch works just fine on my mac).

**Comment by caderaspindrift** [comment]
It throws an error/warning that rmagick should be used instead of RMagick, and the average end user can't do anything to fix it.

**Comment by nodanaonlyzuul** [comment]
Oddly enough - I don't get this error using rmagick 2.13.4.
At least on OSX - but also - this change works for me, I'm going to merge this in and release a version bump shortly.

I think this gem is due for some modernization - period
Can you give me some steps I can take to re-create that deprecation warning? and your OS info?
This gem is due for a modernization and bump of the rmagick dependency. 
I'd like to make sure I don't break your use case or introduce a regression.

**Pull request merged**
