### PR TITLE
separating between html renderer and text renderer

### PR DESCRIPTION
**Pull request by wendy0402**
Hi, I think it is better if we separate the html output and text output. It will be easier to edit it in the future. Therefore I make this pull request. Please review it, and tell me if anything wrong, thanks

### CODE REVIEW

**Comment by rosscooperman** [comment]
:+1:

**Comment by nodanaonlyzuul** [comment]
I like this idea...give me a few days to look this over. Thanks @wendy0402

**Comment by wendy0402** [comment]
right now I'm just do simple refactor, but I hope it will help you all. you are welcome @nodanaonlyzuul

**Comment by wendy0402** [comment]
It's been so long, I think its can be merged if you have look this over :smile:

**Comment by nodanaonlyzuul** [comment]
If this PR were a human it would be in kindergarten!
@wendy0402  - I owe you some thanks and apologies.
I hope you're well - and thanks again.

**Pull request merged**
